// File generated by hand from the Firebase Console download
// (google-services.json) for project `proenroll-4ff13`.
//
// FlutterFire normally generates this file via the `flutterfire`
// CLI. We've inlined the same shape here so the codebase is
// reproducible without that dependency. When you add iOS / Web
// platforms in Firebase Console, replace the matching `FirebaseOptions`
// entries below with the values from the new download.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      // Web Firebase config not provided yet — skip Firebase on web.
      return null;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // iOS GoogleService-Info.plist not provided yet.
        return null;
      default:
        return null;
    }
  }

  /// Values come from the user-supplied `google-services.json`:
  ///   project_number  → messagingSenderId
  ///   mobilesdk_app_id → appId
  ///   api_key.current_key → apiKey
  ///   project_id      → projectId
  ///   storage_bucket  → storageBucket
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxcxKiT-6AjxDs-i3YBz--0qc8GI_xARA',
    appId: '1:1061331368492:android:a2e3e6e23b71191cafef89',
    messagingSenderId: '1061331368492',
    projectId: 'proenroll-4ff13',
    storageBucket: 'proenroll-4ff13.firebasestorage.app',
  );
}
